### PR TITLE
Use changed url name

### LINKED ISSUE #11: Transfer link in profile is broken
On the Profile page, if you have _not_ performed a transfer you get a paragraph with a link, but the link is to the current page.

> You have not sent any records to the NCTR. Start a <a href="http://localhost:8000/profile">new transfer</a> to get started.

Should be to the transfer page.

### PR DESCRIPTION
**Pull request by whikloj**
Resolves #11

### CODE REVIEW

**Comment by whikloj** [comment]
Ohhhh actually I see you're missing the entire FormPreparation class now. So the step is missing. I guess the point was too only hit that page the first time you start a transfer?

**Comment by danloveg** [comment]
You're right, there used to be a form preparation view that I had users hit before they attempted a transfer. That has been superseded by the first part of the transfer form, `forms.AcceptLegal`.

**Comment by whikloj** [comment]
Oh should I have removed the view and template as part of this too?

https://github.com/danloveg/NCTR-Bagit-Record-Transfer/blob/master/bagitobjecttransfer/recordtransfer/views.py#L35-L37

https://github.com/danloveg/NCTR-Bagit-Record-Transfer/blob/master/bagitobjecttransfer/recordtransfer/templates/recordtransfer/formpreparation.html

**Comment by danloveg** [comment]
Good catch, yes, there were a few remaining references to `formpreparation`, I removed them, the template, and the view in [this commit](https://github.com/danloveg/NCTR-Bagit-Record-Transfer/commit/607fea4e83002d2c3ec09773e90d1c832abcc001).

**Pull request merged**
